import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.getAll"]);

  return (
    <>
      <Head>
        <title>Chunkey</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        <h2 className="text-purple-300 text-[3rem] lg:text-[5rem] md:text-[5rem] font-extrabold">
          Chunkey
        </h2>

        <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
          {hello.data ? (
            <p>
              {hello.data.map((d) => (
                <div key={d.id}>{d.id}</div>
              ))}
            </p>
          ) : (
            <p>Loading..</p>
          )}
        </div>
      </div>
    </>
  );
};

export default Home;
