import Head from 'next/head'
import { Header } from './Header'

export const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>Chunkey</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-slate-50 w-full min-h-screen flex flex-col p-4 overflow-y-scroll bg-slate-900">
        <Header />
        {children}
      </div>
    </>
  )
}
